services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped

    ports:
      - "8081:80"

    volumes:
      - /srv/homelab:/srv
      - /srv/homelab/data/filebrowser/database:/database
